"username" = "Имя пользователя"
"password" = "Пароль"
"login" = "Логин"
"confirm" = "Подтвердить"
"cancel" = "Отменить"
"close" = "Закрыть"
"copy" = "Скопировать"
"copied" = "Скопировано"
"download" = "Скачать"
"remark" = "Название"
"enable" = "Включить"
"protocol" = "Протокол"

"loading" = "Загрузка..."
"second" = "Секунд"
"minute" = "Минут"
"hour" = "Часов"
"day" = "Дней"
"check" = "Проверить"
"indefinitely" = "Навсегда"
"unlimited" = "Неограниченно"
"none" = "None"
"qrCode" = "QR код"
"edit" = "Редактировать"
"delete" = "Удалить"
"reset" = "Сбросить"
"copySuccess" = "Успешно скопировано"
"sure" = "Уверен"
"encryption" = "Шифрование"
"transmission" = "Протокол"
"host" = "Хост"
"path" = "Путь"
"camouflage" = "Камуфляж"
"turnOn" = "Включить"
"closure" = "Закрытие"
"domainName" = "Доменное имя"
"additional" = "Дополнительно"
"monitor" = "Мониторинг"
"certificate" = "Сертификат"
"fail" = "Неуспешно"
"success" = "Успешно"
"getVersion" = "Получить версию"
"install" = "Установить"

[menu]
"dashboard" = "Состояние системы"
"inbounds" = "Профили"
"setting" = "Настройки"
"logout" = "Выйти"
"link" = "Другое"

[pages.login]
"title" = "Вход"
"loginAgain" = "Сеанс входа в систему истек, пожалуйста, войдите в систему снова"

[pages.login.toasts]
"invalidFormData" = "Формат входных Данных не верен"
"emptyUsername" = "Пожалуйста, введите имя пользователя"
"emptyPassword" = "Пожалуйста, введите пароль"
"wrongUsernameOrPassword" = "Неверное имя пользователя или пароль. Пробуйте снова"
"successLogin" = "Логин"


[pages.index]
"title" = "Состояние системы"
"memory" = "Память"
"hard" = "Жесткий диск"
"xrayStatus" = "Статус Xray"
"xraySwitch" = "Сменить версию Xray"
"xraySwitchClick" = "Нажмите на версию, чтобы сменить"
"xraySwitchClickDesk" = "Пожалуйста, выбирайте внимательно. Более старые версии могут иметь несовместимые конфигурации. Рекомендуется использовать версию по умолчанию."
"operationHours" = "Время работы"
"operationHoursDesc" = "Время безотказной работы системы с момента ее запуска"
"systemLoad" = "Загрузка системы"
"connectionCount" = "Количество подключений"
"connectionCountDesc" = "Общее количество подключений для всех сетевых карт"
"upSpeed" = "Общая скорость загрузки для всех сетевых карт"
"downSpeed" = "Общая скорость скачивания для всех сетевых карт"
"totalSent" = "Общий трафик загрузки всех сетевых карт с момента запуска системы"
"totalReceive" = "Общий трафик скачивания всех сетевых карт с момента запуска системы"
"xraySwitchVersionDialog" = "Сменить версию Xray"
"xraySwitchVersionDialogDesc" = "Вы уверены, что хотите переключить версию Xray на"
"dontRefreshh" = "Установка находится в процессе... Пожалуйста, не перезагружайте эту страницу"


[pages.inbounds]
"title" = "Профили"
"totalDownUp" = "Общее количество загрузок/скачиваний"
"totalUsage" = "Общее использование"
"inboundCount" = "Количество профилей"
"operate" = "действие"
"enable" = "включить"
"remark" = "название"
"protocol" = "протокол"
"port" = "порт"
"traffic" = "трафик"
"details" = "детали"
"transportConfig" = "Конфигурация протокола"
"expireDate" = "Истекает"
"resetTraffic" = "Сбросить трафик"
"addInbound" = "Добавить профиль"
"addTo" = "Добавить в"
"revise" = "Изменить"
"modifyInbound" = "Изменить профиль"
"deleteInbound" = "Удалить профиль"
"deleteInboundContent" = "Вы уверены, что хотите удалить профиль?"
"resetTrafficContent" = "Вы уверены, что хотите сбросить трафик?"
"copyLink" = "Скопировать ссылку"
"address" = "Адрес"
"network" = "Сеть"
"destinationPort" = "Порт назначения"
"targetAddress" = "Адрес назначения"
"disableInsecureEncryption" = "Отключить небезопасное шифрование"
"monitorDesc" = "Оставьте пустым для прослушивания всех IP-адресов"
"meansNoLimit" = "0 означает без ограничений"
"totalFlow" = "Общий трафик"
"leaveBlankToNeverExpire" = "Оставьте пустым, чтобы никогда не истекал"
"noRecommendKeepDefault" = "Нет никаких особых требований для сохранения значения по умолчанию"
"certificatePath" = "Путь к файлу сертификата"
"certificateContent" = "Содержимое файла certificate.crt"
"publicKeyPath" = "Путь к файлу certificate.crt"
"publicKeyContent" = "Содержимое открытого ключа"
"keyPath" = "Пукть к файлу private.key"
"keyContent" = "Содержимое приватного ключа"
"path" = "Путь"
"requestVersion" = "Версия запроса"
"requestMethod" = "Метод запроса"
"requestPath" = "Путь запроса"
"requestHeader" = "Заголовок запроса"
"name" = "Имя"
"value" = "Значение"
"responseVersion" = "Версия ответа"
"responseStatus" = "Статус ответа"
"responseReason" = "Причина ответа"
"responseHeader" = "Заголовок ответа"
"camouflage" = "Камуфляж"
"encryption" = "Шифрование"
"username" = "Имя пользователя"
"password" = "Пароль"


[pages.inbounds.toasts]
"obtain" = "Получить"

[pages.inbounds.stream.general]
"requestHeader" = "Заголовок запроса"
"name" = "Имя"
"value" = "Значение"

[pages.inbounds.stream.tcp]
"requestVersion" = "Версия запроса"
"requestMethod" = "Метод запроса"
"requestPath" = "Путь запроса"
"responseVersion" = "Версия ответа"
"responseStatus" = "Статус ответа"
"responseStatusDescription" = "Описание статуса ответа"
"responseHeader" = "Заголовок ответа"

[pages.inbounds.stream.quic]
"encryption" = "Шифрование"

[pages.setting]
"title" = "Настройки"
"save" = "Сохранить"
"restartPanel" = "Перезапустить панель"
"restartPanelDesc" = "Вы уверены, что хотите перезапустить панель? Нажмите кнопку ОК, чтобы перезапустить. Если вы не можете получить доступ к панели через 3 секунды, пожалуйста, перейдите на сервер, чтобы просмотреть информацию журнала панели"
"panelConfig" = "Конфигурация панели"
"userSetting" = "Настройки пользователя"
"xrayConfiguration" = "Конфигурация Xray"
"TGReminder" = "Настройки, связанные с TG Bot"
"otherSetting" = "Другие настройки"
"panelListeningIP" = "IP-адрес прослушивания панели"
"panelListeningIPDesc" = "Оставьте поле пустым по умолчанию, чтобы слушать все IP-адреса. Перезапустите панель, чтобы вступило в силу"
"panelPort" = "Порт панели"
"panelPortDesc" = "Перезапустите панель, чтобы она вступила в силу"
"publicKeyPath" = "Путь к файлу certificate.crt панели"
"publicKeyPathDesc" = "Заполните абсолютный путь, начинающийся с '/'. Перезапустите панель, чтобы вступило в силу"
"privateKeyPath" = "Путь к файлу private.key панели"
"privateKeyPathDesc" = "Заполните абсолютный путь, начинающийся с '/'. Перезапустите панель, чтобы вступило в силу"
"panelUrlPath" = "Корневой URL путь панели"
"panelUrlPathDesc" = "Должно начинаться с '/' и заканчиваться на '/'. Перезапустите панель, чтобы вступило в силу"
"oldUsername" = "Текущее имя пользователя"
"currentPassword" = "Текущий пароль"
"newUsername" = "Новое имя пользователя"
"newPassword" = "Новый пароль"
"xrayConfigTemplate" = "Шаблон конфигурации Xray"
"xrayConfigTemplateDesc" = "Создание окончательного файла конфигурации Xray на основе этого шаблона. Перезапустите панель, чтобы вступило в силу"
"telegramBotEnable" = "Включить Telegram Bot"
"telegramBotEnableDesc" = "Перезапустите панель, чтобы вступило в силу"
"telegramToken" = "Токен Telegram"
"telegramTokenDesc" = "Перезапустите панель, чтобы вступило в силу"
"telegramChatId" = "ID чата Telegram (получить с @getidsbot)"
"telegramChatIdDesc" = "Перезапустите панель, чтобы вступило в силу"
"telegramNotifyTime" = "Время уведомления Telegram"
"telegramNotifyTimeDesc" = "Используется формат синхронизации Crontab. (Обратитесь к README.md) Перезапустите панель, чтобы вступило в силу"
"timeZonee" = "Часовой пояс"
"timeZoneDesc" = "Запланированные задачи выполняются в соответствии с этим часовым поясом. Перезапустите панель, чтобы вступило в силу"

[pages.setting.toasts]
"modifySetting" = "Изменить настройки"
"getSetting" = "Получить настройки"
"modifyUser" = "Изменить пользователя"
"originalUserPassIncorrect" = "Текущее имя пользователя или пароль неверны"
"userPassMustBeNotEmpty" = "Новые имя пользователя и пароль не могут быть пустыми"
